[supervisord]
user=root
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:sshd]
command=/usr/sbin/sshd -D -e
user=root
autorestart=true
priority=1
stdout_logfile=/tmp/sshd.out.log
stderr_logfile=/tmp/sshd.err.log

[program:matlab]
command=/bin/bash -c "source /home/matlab/.bashrc && matlab-proxy-app"
user=matlab
directory=/home/matlab/Documents/MATLAB
autorestart=true
priority=2
stdout_logfile=/tmp/matlab.out.log
stderr_logfile=/tmp/matlab.err.log
environment=HOME="/home/matlab",USER="matlab"(base)
 
[program:jupyter]
command=/opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
user=matlab
priority=3
directory=/home/matlab
autorestart=true
stdout_logfile=/tmp/jupyter.out.log
stderr_logfile=/tmp/jupyter.err.log