[supervisord]
nodaemon=true
stdout_logfile=/tmp/supervisord.out.log
stderr_logfile=/tmp/supervisord.err.log

[program:sshd]
command=/usr/sbin/sshd -D -e
user=root
autorestart=true
stdout_logfile=/tmp/sshd.out.log
stderr_logfile=/tmp/sshd.err.log
 
[program:jupyter]
command=/opt/conda/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
user=%%USER_NAME%%
directory=%%HOME_DIR%%
autorestart=true
stdout_logfile=/tmp/jupyter.out.log
stderr_logfile=/tmp/jupyter.err.log